nodes:
  - id: user
    ref: inputs.user

  - id: password
    ref: inputs.password

  - id: fwi
    ref: models.fwi

  - id: plot0
    ref: outputs.fwi-plot0
  
  - id: plot1
    ref: outputs.fwi-plot1

  - id: plot2
    ref: outputs.fwi-plot2

  - id: plot3
    ref: outputs.fwi-plot3

  - id: plot4
    ref: outputs.fwi-plot4

edges:

  - from:
      id: user
    to:
      id: fwi
      port: user

  - from:
      id: password
    to:
      id: fwi
      port: password

  - from:
      id: fwi
      port: fwi-plot0
    to:
      id: plot0

  - from:
      id: fwi
      port: fwi-plot1
    to:
      id: plot1

  - from:
      id: fwi
      port: fwi-plot2
    to:
      id: plot2

  - from:
      id: fwi
      port: fwi-plot3
    to:
      id: plot3

  - from:
      id: fwi
      port: fwi-plot4
    to:
      id: plot4

